spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatisdb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password:
mybatis:
  mapper-locations: classpath:mappers/*.xml