server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mvcdb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password:
logging:
  level:
    root: warn
    re.kaguya.egmv2: debug
# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: re.kaguya.egmv2

#knife4j????
knife4j:
  enable: true    #??knife4j?????@EnableKnife4j??
  setting:
    language: zh_cn   #??
    swagger-model-name: MVC_DEMO  #???SwaggerModel??,??
  #??Swagger?Basic????,???false
  basic:
    enable: false
    # Basic?????
    username: Kaguya
    # Basic????
    password: 123456
mybatis:
  mapper-locations: classpath:mappers/*.xml