server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
mybatis:
  mapper-locations: classpath:mappers/*.xml