server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/images/,classpath:/html/,classpath:/css/,classpath:/js/,classpath:/templates/,file:home/video/
  mvc:
    static-path-pattern: test/**

mybatis:
  mapper-locations: classpath:mappers/*.xml

